### ISSUE TITLE
[Feature] Spring boot Swagger2  적용

### ISSUE THREAD

**Issue by hosunghan-0821** [develkitProject/backend#18]
## 목적
> Swagger 적용하여 api 상세하게 나타낼 수 있도록함
## 작업 상세 내용
-1. Swagger 개념 이해 및 프로젝트 적용
-2. 각 controller 정의

**Comment by cheoljun0422** [comment]
chat, error, login 부분 확인 부탁드립니다.

**Comment by hosunghan-0821** [comment]
고생하셧슴다
